[geometry]
model = "../model/finfet.stl"

[simulation]
particle_count = 10000000
time_step = 0.1
iterations = 1000
random_seed = 12345
compute_kappa = false
initial_temperature = 300
grid_xyz = [22, 36, 30]
progress_temperature_summary_only = true

[boundary]
boundary_position = [
  [0.1, 0.0, 0.0, 0.45, 1.0, 1.0],
  [0.55, 0.0, 0.0, 0.9, 1.0, 1.0],
  [-0.01, 0.0, 0.0, 0.01, 1.0, 1.0],
  [0.99, 0.0, 0.0, 1.01, 1.0, 1.0],
  [0.0, -0.01, 0.0, 1.0, 0.01, 1.0],
  [0.0, 0.99, 0.0, 1.0, 1.01, 1.0],
  [0.0, 0.0, -0.01, 1.0, 1.0, 0.01]
]
boundary_conditions = ["R", "R", "P", "P", "P", "P", "T"]
boundary_values = [1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 300.0]
periodic_pair = [
  [-0.01, 0.0, 0.0, 0.01, 1.0, 1.0], [0.99, 0.0, 0.0, 1.01, 1.0, 1.0],
  [0.0, -0.01, 0.0, 1.0, 0.01, 1.0], [0.0, 0.99, 0.0, 1.0, 1.01, 1.0]
]

[heat_source]
enabled = true
min = [0.3, 0.6, 0.7]
max = [0.7, 0.8, 1.0]
power_density = 1.0e20

profile = "gaussian"
center = [0.5, 0.7, 1.0]
sigma  = [0.0, 0.04, 0.10]

[io]
material_folder = "../material/Si/"
output_folder = "results/FinFET_heat1e20/"
