[geometry]
model = "box"
sizes = [1000, 1000, 1000]

[simulation]
particle_count = 10000
time_step = 0.1
iterations = 100000
compute_kappa = true
grid_xyz = [10, 1, 1]

[boundary]
boundary_position = [[0, 0.5, 0.5], [1, 0.5, 0.5]]
boundary_conditions = ["T", "T", "P"]
boundary_values = [301, 299]
periodic_pair = [[0.5, 0, 0.5], [0.5, 1, 0.5], [0.5, 0.5, 0], [0.5, 0.5, 1]]

[io]
material_folder = "material/Si/"
output_folder = "results/Cross_1000nm_300K/"
