[geometry]
model = "box"
sizes = [100, 100, 100]

[simulation]
particle_count = 10000
time_step = 0.1
iterations = 5000
compute_kappa = true
initial_temperature = "linear"
grid_xyz = [10, 1, 1]

[boundary]
boundary_position = [
  [-0.01, 0.0, 0.0, 0.01, 1.0, 1.0],
  [0.99, 0.0, 0.0, 1.01, 1.0, 1.0],
  [0.0, -0.01, 0.0, 1.0, 0.01, 1.0],
  [0.0, 0.99, 0.0, 1.0, 1.01, 1.0],
  [0.0, 0.0, -0.01, 1.0, 1.0, 0.01],
  [0.0, 0.0, 0.99, 1.0, 1.0, 1.01]
]
boundary_conditions = ["T", "T", "P", "P", "P", "P"]
boundary_values = [301, 299]
periodic_pair = [
  [0.0, -0.01, 0.0, 1.0, 0.01, 1.0], [0.0, 0.99, 0.0, 1.0, 1.01, 1.0],
  [0.0, 0.0, -0.01, 1.0, 1.0, 0.01], [0.0, 0.0, 0.99, 1.0, 1.0, 1.01]
]

[io]
material_folder = "material/Si/"
output_folder = "results/Cross_100nm/"
