[geometry]
model = "Model/finfet_A.stl"

[simulation]
particles = 50000
timestep = 0.1
iterations = 1000
compute_thermal_conductivity = false
temp_dist = "mean"
subvolumes_mode = "grid"
subvolumes_grid = [22, 36, 30]

[boundary]
bound_pos_mode = "relative"
bound_pos_points = [
  [0.5, 0.5, 0.0],
  [0.0, 0.5, 0.15],
  [1.0, 0.5, 0.15],
  [0.5, 0.0, 0.2],
  [0.5, 1.0, 0.2],
  [0.1, 0.5, 0.3333333333],
  [0.9, 0.5, 0.3333333333],
  [0.3181818182, 0.5, 0.7],
  [0.6818181818, 0.5, 0.7],
  [0.5, 0.5, 1.0]
]
bound_cond = ["T", "P", "P", "P", "P", "R", "R", "R", "R", "R"]
bound_values = [300.0, 1.0, 1.0, 1.0, 1.0, 1.0]
connect_pos_mode = "relative"
connect_pos_points = [
  [0.0, 0.5, 0.15], [1.0, 0.5, 0.15],
  [0.5, 0.0, 0.2], [0.5, 1.0, 0.2]
]

[io]
mat_folder = "Material/Si/"
results_folder = "results/FinFET_HeatSource_A/"

[heat_source]
enabled = true
mode = "relative"
min = [0.43, 0.43, 0.88]
max = [0.57, 0.57, 0.99]
power_density = 7.0e19
